export const WEBSITE_COPY = {
  hero: {
    eyebrow: "Kostenlos · gemeinsam gebaut · in 20 Minuten live",
    title: "Deine Website als Social Media Managerin. Wir bauen sie mit dir. Kostenlos.",
    sub: "Plus Kundenportal, Profil-Check-Vorlage und der DM-Text, mit dem Frauen ohne eigene Follower ihren ersten Kunden bekommen.",
    cta: "Meine Website sichern",
    ghost: "Wie ist das kostenlos? ↓",
  },
  logos: {
    eyebrow: "Gebaut mit Tools von",
    items: [
      { src: "/logos/wix.svg", alt: "Wix" },
      { src: "/logos/base44.svg", alt: "Base44" },
      { src: "/logos/canva.svg", alt: "Canva" },
      { src: "/logos/capcut.svg", alt: "CapCut" },
      { src: "/logos/meta.svg", alt: "Meta" },
    ],
  },
  why: {
    eyebrow: "Warum Social Media Managerin",
    heading: "Kein Produkt. Kein Lager. Ein Kunde reicht.",
    sub: "Ein überschaubares Geschäftsmodell, das du mit Fähigkeiten startest, die du dir Schritt für Schritt aneignen kannst.",
    cards: [
      "3,2 Millionen Unternehmen in Deutschland — die meisten posten nicht",
      "Ein Kunde zahlt 800–1.500 € im Monat",
      "Deine eigenen Follower sind egal — der Kunde braucht sie nicht",
      "5 Stunden pro Woche, remote",
      "Neben Job oder Studium starten",
      "Kein Vorwissen — Handy, CapCut, ein System",
    ],
  },
  package: {
    eyebrow: "Dein Startpaket",
    heading: "Alles, was du für den ersten Kunden brauchst.",
    sub: "Kein Sammelsurium aus Vorlagen, sondern ein einsatzbereiter Startpunkt für dein Angebot.",
    cards: [
      "Deine Website — im Onboarding-Call gemeinsam gebaut, mit Domain",
      "Kundenportal — deine Kunden geben Content frei, ohne WhatsApp-Chaos",
      "Profil-Check-Vorlage — die 5 Minuten, die dich buchbar machen",
      "DM-Skript — wörtlich, getestet, ohne Verkaufsgefühl",
      "5-Branchen-Liste — wer Budget hat und wer nicht",
      "Onboarding-Call — 20 Minuten mit uns, live geschaltet",
    ],
  },
  value: {
    eyebrow: "Der komplette Start",
    heading: "Dein Fundament, fertig zum Losgehen.",
    sub: "Du bekommst die Werkzeuge und setzt die Website mit uns gemeinsam live.",
    items: [
      { item: "Website mit Domain", value: "1.500 €" },
      { item: "Kundenportal", value: "800 €" },
      { item: "Akquise-Toolkit", value: "297 €" },
      { item: "Onboarding-Call", value: "150 €" },
      { item: "Masterclass-Zugang", value: "197 €" },
    ],
    total: "2.944 €",
    price: "0 €",
    footnote: "Einziges Kostenstück: das Hosting deiner Website bei Wix — so viel wie Netflix. Das geht direkt an Wix, nicht an uns.",
  },
  photoBand: {
    heading: "6,9 Millionen Views. Der erste Kunde kam trotzdem über einen Profil-Check.",
  },
  steps: {
    eyebrow: "In drei Schritten",
    heading: "Von der Eintragung bis zum Link in deiner Bio.",
    sub: "Wir halten den Weg bewusst kurz und setzen ihn gemeinsam mit dir um.",
    items: [
      { title: "Zwei Minuten eintragen", body: "Vorname, E-Mail, Nummer." },
      { title: "Onboarding-Call", body: "Wir bauen deine Seite gemeinsam und schalten sie live." },
      { title: "Link in die Bio", body: "Dein Business hat ab jetzt eine Adresse." },
    ],
  },
  honest: {
    eyebrow: "Wie ist das kostenlos?",
    heading: "Der ehrliche Grund.",
    body: "Wix und Base44 zahlen uns, wenn du ihre Tools nutzt. Deshalb kostet dich das nichts. Ein Teil der Frauen will danach mit uns weitermachen — mit persönlicher Begleitung bis zum ersten Kunden. Das ist unser Geschäft. Ob du das willst, entscheidest du später. Erst mal bekommst du die Website.",
  },
  laura: {
    eyebrow: "Der Weg dahinter",
    heading: "Laura Mercedes",
    quote: "6,9 Mio. Views in einem Monat. Erster Kunde: ein Café, über einen 5-Minuten-Profil-Check. Heute zeige ich Frauen, wie sie das ohne eigene Reichweite machen.",
    stats: ["6,9 Mio. Views", "0 Ads", "Remote"],
  },
  testimonials: [] as { src: string; alt: string }[],
  faq: {
    eyebrow: "Offen beantwortet",
    heading: "Die Fragen vor deinem Start.",
    sub: "Damit du weißt, was du bekommst — und was nicht.",
    items: [
      { question: "Wo ist der Haken?", answer: "Es gibt keinen versteckten Kaufzwang. Wix und Base44 vergüten uns, wenn du ihre Tools nutzt; manche Frauen entscheiden sich später freiwillig für unsere persönliche Begleitung." },
      { question: "Was kostet mich das wirklich?", answer: "Unser Startpaket und der gemeinsame Onboarding-Call kosten dich 0 €. Nur das Hosting deiner Website bei Wix bezahlst du direkt an Wix — ungefähr so viel wie ein Netflix-Abo." },
      { question: "Wie lange dauert das?", answer: "Der Onboarding-Call dauert etwa 20 Minuten. Wenn deine Angaben vollständig sind, bauen wir die Seite mit dir und schalten sie direkt live." },
      { question: "Brauche ich Vorkenntnisse?", answer: "Nein. Du brauchst ein Handy, einen Laptop und die Bereitschaft, die Schritte mit uns umzusetzen; die Technik erklären wir im Call." },
      { question: "Ich habe kaum Follower — geht das trotzdem?", answer: "Ja. Du arbeitest für die Reichweite deiner Kundinnen und Kunden, nicht für deine eigene; der Profil-Check hilft dir, auch ohne große Community ins Gespräch zu kommen." },
      { question: "Ich habe einen Vollzeitjob.", answer: "Der Einstieg ist neben Job oder Studium gedacht. Plane für den Anfang ungefähr fünf konzentrierte Stunden pro Woche ein und entscheide selbst, wann du skalierst." },
      { question: "Wie finde ich Kunden?", answer: "Du bekommst eine Branchen-Liste, den Profil-Check und ein getestetes DM-Skript. Damit kannst du gezielt Unternehmen ansprechen, bei denen du konkretes Verbesserungspotenzial siehst." },
      { question: "Muss ich das Wix-Abo behalten?", answer: "Nur solange deine Website dort online bleiben soll. Das Abo läuft direkt zwischen dir und Wix; du kannst es nach den dort geltenden Bedingungen ändern oder kündigen." },
    ],
  },
  final: { eyebrow: "Dein nächster Schritt", heading: "Deine Website wartet.", cta: "Meine Website sichern" },
  modal: {
    step1: "Wohin sollen wir deine Website schicken?",
    step2: "Wir bauen sie gemeinsam mit dir — am Telefon",
    helper: "20 Minuten, wir schalten deine Seite live und beantworten deine Fragen. Kein Verkaufsgespräch.",
    consent: "Ich bin einverstanden, dass ihr mich anruft und mir E-Mails schickt",
    next: "Weiter",
    submit: "Meine Website sichern",
  },
  partnerNotice: "Links zu Wix und Base44 sind Partnerlinks.",
} as const;

export const WEBSITE_THANKS = {
  eyebrow: "Fast fertig",
  title: "Wir rufen dich an.",
  sub: "Innerhalb von 24 Stunden, meistens schneller. 20 Minuten, dann ist deine Seite live.",
  videoId: "",
  stepsEyebrow: "Was jetzt passiert",
  stepsHeading: "Drei kurze Schritte bis zu deiner Seite.",
  stepsSub: "Du musst nichts vorbereiten — wir führen dich durch den Ablauf.",
  steps: [
    { title: "Wir prüfen deine Angaben", body: "Deine Eintragung landet direkt bei unserem Team." },
    { title: "Wir rufen dich an", body: "Innerhalb von 24 Stunden, meistens schneller." },
    { title: "Wir schalten deine Seite live", body: "Im 20-Minuten-Call setzen wir die letzten Schritte gemeinsam um." },
  ],
  phoneHeading: "Speicher dir unsere Nummer, damit du den Anruf erkennst:",
  whatsappNumber: "+49 151 72550097",
  calendlyHeading: "Oder such dir direkt deinen Slot",
  setterCalendlyUrl: "",
} as const;
